name: issue on failure

on:
 workflow_run:
  workflows: ["hello-world-pipeline"]
  types:
   - completed

jobs:
   create_issue:
      if: ${{ github.event.workflow_run.conclusion == 'failure' }}
      runs-on: ubuntu-latest
      steps:

        name: create issue on failure
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
         gh issue create \
            --title "Pipeline Failure 🚨" \
            --body "The workflow hello-world-pipeline failed. Please check logs."
         


  
   